# Generated by Django 2.2 on 2020-04-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_info_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=10, unique=True)),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
