# Generated by Django 2.2 on 2020-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='correct',
            field=models.CharField(default='', max_length=8),
        ),
    ]
